Adding the missing Legos from the runbooks
unskript/Awesome-CloudOps-Automation pull request #14
Opened 2022-09-03 04:32 UTC by jayasimha-raghavan-unskript

## Description
Adding the missing legos from the Runbooks.

### Testing
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 

### Checklist:
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

2022-09-07 15:46 UTC, abhishek-unskript requested changes

2022-09-07 15:46 UTC, abhishek-unskript commented on MySQL/legos/mysql_read_query/README.md
> +This Lego queries the database and retrieves long run queries.
this is not the correct description I think

2022-09-07 15:46 UTC, abhishek-unskript commented on MySQL/legos/mysql_read_query/README.md
> +This Lego takes twoinput query and param.
Parameters should be shown in detail with examples?

2022-09-07 15:46 UTC, abhishek-unskript commented on MySQL/legos/README.md
> +* [Run MySQL Query](./mysql_read_query/README.md)
There are two legos underneath, not one

2022-09-07 15:46 UTC, abhishek-unskript commented on MySQL/legos/mysql_kill_long_query/README.md
> +This Lego queries the database and retrieves long run queries.
"retrieves long running queries"

2022-09-07 15:46 UTC, abhishek-unskript commented on MySQL/legos/mysql_kill_long_query/mysql_read_query.json
> +  }
File name and entry function name are not correct.

2022-09-07 15:46 UTC, abhishek-unskript commented on MySQL/legos/mysql_kill_long_query/mysql_read_query.py
> +
I don't think this is the correct lego. Perhaps you have copied the wrong files. Please relook thru this diff.

2022-10-04 20:22 UTC, twishek approved these changes

2022-10-04 20:23 UTC, abhishek-unskript approved these changes

2022-10-04 20:24 UTC, merged