Action: Github Get Open Branches
unskript/Awesome-CloudOps-Automation pull request #264
Opened 2023-02-27 11:09 UTC by shloka-bhalgat-unskript

## Description
### [Issue-255](https://github.com/unskript/Awesome-CloudOps-Automation/issues/255)

Added a new action to get open branches for a user in a repository. (Limit-100)

### Testing
<img width="918" alt="Screenshot 2023-02-27 at 4 34 45 PM" src="https://user-images.githubusercontent.com/110628398/221548233-0bd16238-545f-462a-bd84-24ca98e2381e.png">

### Checklist:
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

2023-02-28 19:20 UTC, dougsillars commented on Github/legos/github_get_open_branches/github_get_open_branches.py
> +        repo_name = owner+"/"+repository
if repository is the full  name (unskript/Awesome-CloudOps-Automation)
does this one make it unskript/unskript/Awesome-CloudOps-Automation?

2023-02-28 19:21 UTC, dougsillars requested changes
i think repository should not have the owner/ - but just the name of the repo.  Maybe just change the comment to make that clear.

2023-03-01 16:44 UTC, dougsillars approved these changes
Thanks!  LGTM

2023-03-02 10:27 UTC, harshal-netserv commented on Github/legos/github_get_open_branches/github_get_open_branches.py
> +            return [e.data]
@shloka-bhalgat-unskript we should raise the exception instead of return.

2023-03-29 10:58 UTC, harshal-netserv approved these changes

2023-03-29 16:40 UTC, merged