Action: Github Delete Branch
unskript/Awesome-CloudOps-Automation pull request #273
Opened 2023-02-28 18:21 UTC by shloka-bhalgat-unskript

## Description
### [Issue-257](https://github.com/unskript/Awesome-CloudOps-Automation/issues/257)

Added a new action to delete a branch

### Testing
<img width="700" alt="Screenshot 2023-02-28 at 11 03 34 PM" src="https://user-images.githubusercontent.com/110628398/221944603-df5cb753-66ca-4996-99cf-d66dc1326c1d.png">

### Checklist:
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

2023-03-01 01:05 UTC, dougsillars requested changes
in the description you say repository is "unskript/Awesome-CloudOps-Automation"
But I think it should just be "Awesome-CloudOps-Automation"

This is once in the readme, and once in the py file

2023-03-03 06:20 UTC, shloka-bhalgat-unskript commented
Changes made

2023-03-10 10:31 UTC, harshal-netserv approved these changes

2023-03-10 13:01 UTC, dougsillars approved these changes

2023-03-10 13:01 UTC, merged