Action: Get Github Team
unskript/Awesome-CloudOps-Automation pull request #274
Opened 2023-02-28 18:24 UTC by shloka-bhalgat-unskript

## Description
### [Issue-254](https://github.com/unskript/Awesome-CloudOps-Automation/issues/254)

### Testing
<img width="703" alt="Screenshot 2023-02-28 at 11 01 05 PM" src="https://user-images.githubusercontent.com/110628398/221945136-1e192f0a-de57-424a-af5f-056de2365468.png">

### Checklist:
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

2023-03-01 01:35 UTC, dougsillars requested changes
This lego takes in the team name - and outputs the team name.

Can we just list the entire response as the output - that way the user can get the users or other features of the team name?

2023-03-01 08:19 UTC, shloka-bhalgat-unskript commented
I have added the relevant team details that are returned by this API viz member count, repo count, permission, privacy.

2023-03-02 02:39 UTC, dougsillars approved these changes

2023-03-02 21:38 UTC, amit-chandak-unskript approved these changes

2023-03-02 21:38 UTC, merged