Action: Github Close PR
unskript/Awesome-CloudOps-Automation pull request #299
Opened 2023-03-03 06:15 UTC by shloka-bhalgat-unskript

## Description
### [Issue-247](https://github.com/unskript/Awesome-CloudOps-Automation/issues/247)

### Testing

<img width="700" alt="Screenshot 2023-03-02 at 6 52 57 PM" src="https://user-images.githubusercontent.com/110628398/222645579-77b64232-904a-4756-b31e-f92ae8ad93f1.png">

### Checklist:
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

2023-03-03 07:22 UTC, shloka-bhalgat-unskript commented
Added raise exception changes for merged files in this PR

2023-03-09 14:55 UTC, dougsillars submitted a review, later dismissed

2023-03-15 14:02 UTC, dougsillars submitted a review, later dismissed

2023-03-17 19:14 UTC, dougsillars requested changes
Readme needs a small change, otherwise this looks good

2023-03-17 19:14 UTC, dougsillars commented on Github/legos/github_close_pull_request/README.md
> +
PR number should be here as well, correct?

2023-03-29 11:05 UTC, harshal-netserv approved these changes

2023-03-29 16:41 UTC, merged