Update: Github List Stargazers
unskript/Awesome-CloudOps-Automation pull request #342
Opened 2023-03-13 10:51 UTC by shloka-bhalgat-unskript

## Description

1. Added starred at
2. Changed to get last 100 stargazers

### Testing
<img width="919" alt="Screenshot 2023-03-13 at 3 23 27 PM" src="https://user-images.githubusercontent.com/110628398/224680825-a49150ea-0ea9-4395-bc6e-8ebd869ffecc.png">

### Checklist:
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

2023-03-14 00:22 UTC, dougsillars reviewed
did you change the code?  I think the code is showing the first 100 stargazers.

2023-03-14 00:23 UTC, dougsillars requested changes
When I looked at the Action - it was the first 100.  Did the code change, or just the comment?

2023-03-14 06:26 UTC, shloka-bhalgat-unskript commented on Github/legos/github_list_stargazers/github_list_stargazers.py
> +        for star in stars[len(list(stars))-100:]:
So here we are getting the last 100 stargazers. Earlier it was first 100

2023-03-14 09:57 UTC, harshal-netserv approved these changes

2023-03-15 04:33 UTC, dougsillars approved these changes

2023-03-15 04:33 UTC, merged