[Action] AWS Get EBS Volumes for Low Usage
unskript/Awesome-CloudOps-Automation pull request #375
Opened 2023-03-22 11:40 UTC by harshal-netserv

## Description
AWS Get EBS Volumes for Low Usage

### Testing
<img width="712" alt="image" src="https://user-images.githubusercontent.com/63058785/226893366-9f7a6edb-5eb4-4c7c-8e9d-d6b533012185.png">

### Checklist:
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

2023-03-22 13:28 UTC, dougsillars submitted a review, later dismissed

2023-03-23 07:39 UTC, shloka-bhalgat-unskript commented on AWS/legos/aws_get_ebs_volume_for_low_usage/aws_get_ebs_volume_for_low_usage.py
> +        return (True, [])
Same thing here, this should send None

2023-03-23 15:53 UTC, dougsillars requested changes

2023-03-23 15:53 UTC, dougsillars commented on AWS/legos/aws_get_ebs_volume_for_low_usage/aws_get_ebs_volume_for_low_usage.py
> +                    if v['Average'] < 10:
could the 10% also be an input parameter?

so you could do 5% for 30 days?

2023-04-10 18:17 UTC, closed without merging