Action: AWS List Hosted Zones
unskript/Awesome-CloudOps-Automation pull request #428
Opened 2023-04-10 09:14 UTC by shloka-bhalgat-unskript

## Description
[Issue-415](https://github.com/unskript/Awesome-CloudOps-Automation/issues/415)

### Testing
<img width="891" alt="Screenshot 2023-04-10 at 2 42 19 PM" src="https://user-images.githubusercontent.com/110628398/230872337-8ae4d787-147c-4d36-92ee-0deb8bea25c3.png">

### Checklist:
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

2023-04-10 13:45 UTC, dougsillars requested changes
small edit on the JOSN

2023-04-10 13:45 UTC, dougsillars commented on AWS/legos/aws_list_hosted_zones/aws_list_hosted_zones.json
> +  "action_supports_poll": "true"
can you add an action_categories parameter to the JSON?

2023-04-11 22:42 UTC, dougsillars approved these changes

2023-04-12 17:05 UTC, harshal-netserv approved these changes

2023-04-12 22:39 UTC, merged