Action: AWS Get TTL for Route53 records
unskript/Awesome-CloudOps-Automation pull request #430
Opened 2023-04-10 09:56 UTC by shloka-bhalgat-unskript

## Description
### [Issue-414](https://github.com/unskript/Awesome-CloudOps-Automation/issues/414)
### Testing
<img width="901" alt="Screenshot 2023-04-10 at 3 19 42 PM" src="https://user-images.githubusercontent.com/110628398/230879481-4962faf7-38a4-44a6-bd1d-ee82f4fc32bb.png">

### Checklist:
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

2023-04-10 13:46 UTC, dougsillars requested changes
JSON needs the category

2023-04-10 13:46 UTC, dougsillars commented on AWS/legos/aws_get_ttl_for_route53_records/aws_get_ttl_for_route53_records.json
> +  "action_supports_poll": "true"
can you add an action_categories parameter to the JSON?

2023-04-12 17:06 UTC, harshal-netserv approved these changes

2023-04-13 11:24 UTC, dougsillars approved these changes

2023-04-13 11:24 UTC, merged