Runbook: Change EBS Volume to GP3 Type
unskript/Awesome-CloudOps-Automation pull request #481
Opened 2023-04-13 10:46 UTC by shloka-bhalgat-unskript

## Description

### [Issue-461](https://github.com/unskript/Awesome-CloudOps-Automation/issues/461)

### Testing
Since there were no failing cases the remediation lego won't run

https://user-images.githubusercontent.com/110628398/231735563-1b65b145-2a5f-4216-b932-15865fe0eee7.mov

### Checklist:
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

2023-04-13 13:05 UTC, dougsillars requested changes

2023-04-13 13:05 UTC, dougsillars commented on AWS/Change_AWS_EBS_Volume_To_GP3_Type.json
> +    "uuid": "",
needs UUID?

2023-04-13 13:08 UTC, shloka-bhalgat-unskript commented on AWS/Change_AWS_EBS_Volume_To_GP3_Type.json
> +    "uuid": "",
Done

2023-04-13 13:30 UTC, dougsillars approved these changes

2023-04-15 03:08 UTC, amit-chandak-unskript commented
@shloka-bhalgat-unskript this is a remediation runbook, right? that means the check corresponding to this runbook will return failed objects, which can be passed as param to this runbook. So having region as the runbook param doesnt look right.  Whats the check corresponding to this runbook?

2023-04-15 03:08 UTC, amit-chandak-unskript requested changes
Take care of comments

2023-04-17 08:17 UTC, shloka-bhalgat-unskript commented
> @shloka-bhalgat-unskript this is a remediation runbook, right? that means the check corresponding to this runbook will return failed objects, which can be passed as param to this runbook. So having region as the runbook param doesnt look right. Whats the check corresponding to this runbook?

@amit-chandak-unskript region is an optional parameter. We had decided to have this as a part of the parameters because if the user intends to run the runbook by itself than through the healthcheck  feature, it needs to have region as an optional param. (so that the `list all aws regions` lego is triggered in the runbook)

2023-04-17 18:52 UTC, amit-chandak-unskript commented
> > @shloka-bhalgat-unskript this is a remediation runbook, right? that means the check corresponding to this runbook will return failed objects, which can be passed as param to this runbook. So having region as the runbook param doesnt look right. Whats the check corresponding to this runbook?
> 
> @amit-chandak-unskript region is an optional parameter. We had decided to have this as a part of the parameters because if the user intends to run the runbook by itself than through the healthcheck feature, it needs to have region as an optional param. (so that the `list all aws regions` lego is triggered in the runbook)

@shloka-bhalgat-unskript i can understand region parameter, but how is the information from the failed objects from the check corresponding to this remediation runbook passed? It should have an optional parameter list of ebs volumes (volume id, region) tuple.

2023-04-18 13:41 UTC, dougsillars approved these changes

2023-04-19 04:07 UTC, amit-chandak-unskript approved these changes

2023-04-19 04:07 UTC, merged