Check Action: Get timed out AWS Lambda
unskript/Awesome-CloudOps-Automation pull request #528
Opened 2023-04-24 10:59 UTC by shloka-bhalgat-unskript

## Description
[Issue-434](https://github.com/unskript/Awesome-CloudOps-Automation/issues/434)

### Testing
<img width="919" alt="Screenshot 2023-04-24 at 4 24 16 PM" src="https://user-images.githubusercontent.com/110628398/233977461-16422307-f816-4cb9-a892-339fcaebcada.png">

### Checklist:
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

2023-04-24 18:42 UTC, dougsillars approved these changes

2023-04-26 12:25 UTC, harshal-netserv approved these changes

2023-04-27 16:12 UTC, dougsillars approved these changes

2023-05-04 22:39 UTC, amit-chandak-unskript commented
@shloka-bhalgat-unskript did we test this lego? Please dont attach png file with check passing, it doesnt help.

2023-05-08 22:55 UTC, amit-chandak-unskript requested changes
Attach failed Timed out AWS lambdas png

2023-05-15 06:44 UTC, shloka-bhalgat-unskript commented
> Attach failed Timed out AWS lambdas png

@amit-chandak-unskript I had tried to test it out on out existing AWS lambda functions but none of them are working. So basically there is no data to capture for timed out lambdas.

2023-06-06 18:56 UTC, amit-chandak-unskript approved these changes

2023-06-06 18:56 UTC, merged