Edit 2
unskript/Awesome-CloudOps-Automation pull request #605
Opened 2023-05-04 21:47 UTC by kaushik-bandodkar-unskript

## Description
Please include a summary of the change, motivation and context.

### Testing
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 

### Checklist:
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

2023-05-07 16:50 UTC, abhishek-unskript approved these changes

2023-05-08 22:59 UTC, amit-chandak-unskript commented on AWS/legos/aws_create_redshift_query/aws_create_redshift_query.py
> +    handle,
Why do we have an extra new line above handle? @kaushik-bandodkar-unskript

2023-05-08 23:00 UTC, amit-chandak-unskript commented on AWS/legos/aws_create_bucket/aws_create_bucket.py
> +        description=('The Canned ACL to apply to the bucket. Possible values: '
I am interested in the pylint error reported here, want to see if there is a better way of fixing this.

2023-05-08 23:01 UTC, amit-chandak-unskript requested changes
Please take care of review comments

2023-05-10 22:43 UTC, amit-chandak-unskript approved these changes

2023-05-10 22:51 UTC, merged