add AWS SES email action
unskript/Awesome-CloudOps-Automation pull request #755
Opened 2023-06-19 11:48 UTC by dougsillars

New action:

Using AWS Simple Email Server, this action takes in 
Sender email
receiver email
subject
Body
region

And sends an email.

2023-07-14 00:16 UTC, abhishek-unskript commented on AWS/legos/aws_send_email/aws_send_email.py
> +    print(response)
assert on error

2023-07-14 00:17 UTC, abhishek-unskript requested changes
error handling is missing. please add

2023-07-14 11:55 UTC, dougsillars commented on AWS/legos/aws_send_email/aws_send_email.py
> +    print(response)
fixed

2023-09-07 07:25 UTC, abhishek-unskript submitted a review, later dismissed

2023-09-29 07:37 UTC, abhishek-unskript approved these changes

2023-09-29 07:37 UTC, merged