En 5153 jayasimha
unskript/Awesome-CloudOps-Automation pull request #923
Opened 2023-11-02 15:26 UTC by jayasimha-raghavan-unskript

## Description
Please include a summary of the change, motivation and context.

* Brings in Support for `--run` option that implements running all possible options in a single command
* Code reorganization into sepearte files based on function to make it easier to maintain 

### Testing
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 

### Checklist:
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

2023-11-04 04:41 UTC, amit-chandak-unskript commented on unskript-ctl/unskript_ctl_list.py
> +        contents = None
Put read under try catch as well

2023-11-04 04:47 UTC, amit-chandak-unskript commented on unskript-ctl/unskript_ctl_list.py
> +    lp.add_argument('-r',
this doesnt make sense, -r, -c, --failed-checks are all options after -l, so why are these arguments defined at this level? Look at how i do it hierarchical in add_creds.py

2023-11-04 04:49 UTC, amit-chandak-unskript commented on unskript-ctl/unskript_ctl_show.py
> +    parser.add_argument('-s',
WE shouldnt be duplicating this in each hierarchy, each hierarchy should only show option at that level, not its parent.

2023-11-04 04:51 UTC, amit-chandak-unskript requested changes
all argument parser need to be fixed

2023-11-04 20:47 UTC, jayasimha-raghavan-unskript commented
PR Comments taken care of
```
(base) root@5360b59f5f3b:/unskript/data/actions/STORE/new# python ./unskript_ctl.py -r -h
usage: unskript_ctl.py [-h] [--script SCRIPT] [--runbook [RUNBOOK ...]] [--check [CHECK ...]] [--report]

optional arguments:
  -h, --help            show this help message and exit
  --script SCRIPT       Run script
  --runbook [RUNBOOK ...]
                        Run the given runbook FILENAME [-RUNBOOK_PARM1 VALUE1] etc..
  --check [CHECK ...]   Run checks
  --report              Report results
(base) root@5360b59f5f3b:/unskript/data/actions/STORE/new# python ./unskript_ctl.py -l -h
usage: unskript_ctl.py [-h] [-r] [--failed-checks ...] [-c ...] [--credential]

optional arguments:
  -h, --help            show this help message and exit
  -r, --runbooks        List Runbooks
  --failed-checks ...   List Failed checks
  -c ..., --checks ...  List Checks
  --credential          List Credential
(base) root@5360b59f5f3b:/unskript/data/actions/STORE/new# python ./unskript_ctl.py -s -h
usage: unskript_ctl.py [-h] [--audit-trail ...] [--failed-logs ...]

optional arguments:
  -h, --help         show this help message and exit
  --audit-trail ...  Show Audit Trail
  --failed-logs ...  Show Failed Logs
(base) root@5360b59f5f3b:/unskript/data/actions/STORE/new# python ./unskript_ctl.py -d -h
usage: unskript_ctl.py [-h] [--start ...] [--stop]

optional arguments:
  -h, --help   show this help message and exit
  --start ...  Start debug session. Example [--start --config /tmp/config.ovpn]
  --stop       Stop current debug session
(base) root@5360b59f5f3b:/unskript/data/actions/STORE/new# python ./unskript_ctl.py -h
usage: unskript-ctl [-h] [-l ...] [-r ...] [-s ...] [-d ...] [--create-credential ...]

Welcome to unSkript CLI Interface VERSION: 0.1.0

optional arguments:
  -h, --help            show this help message and exit
  -l ..., --list ...    List Options
  -r ..., --run ...     Run Options
  -s ..., --show ...    Show Options
  -d ..., --debug ...   Debug Options
  --create-credential ...
                        Create Credential [-creds-type creds_file_path]
(base) root@5360b59f5f3b:/unskript/data/actions/STORE/new# 
```

2023-11-06 04:58 UTC, amit-chandak-unskript commented
@jayasimha-raghavan-unskript i dont think my comments are resolved?

2023-11-06 04:58 UTC, amit-chandak-unskript approved these changes

2023-11-06 04:58 UTC, merged